pipeline:
  name: TidBit - Cache Intelligence
  identifier: TidBit_Cache_Intelligence
  projectIdentifier: mycitest
  orgIdentifier: abhilabs
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: TidBit_Demo
        build: <+input>
  stages:
    - stage:
        name: React Build
        identifier: React_Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      npm ci
                      npm run build
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.abhishek_docker_connector
                    repo: abhiharnesscxe/tidbit-react-app
                    tags:
                      - <+pipeline.sequenceId>
                    caching: true
